apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uv6g2skc7-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uv6g2skc7-dotnet-basic-gitops