apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uv6g2skc7-dotnet-basic
  janus-idp.io/tekton: uv6g2skc7-dotnet-basic
  backstage.io/kubernetes-id: uv6g2skc7-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uv6g2skc7-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
